/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package org.relique.jdbc.csv;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLELINECOMMENT = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int DISTINCT = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int UNSIGNEDINT = 10;
  /** RegularExpression Id. */
  int UNSIGNEDNUMBER = 11;
  /** RegularExpression Id. */
  int DIGITS = 12;
  /** RegularExpression Id. */
  int EXPONENT = 13;
  /** RegularExpression Id. */
  int TYPESUFFIX = 14;
  /** RegularExpression Id. */
  int NULL = 15;
  /** RegularExpression Id. */
  int CURRENT_DATE = 16;
  /** RegularExpression Id. */
  int CURRENT_TIME = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int IS = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int LIKE = 23;
  /** RegularExpression Id. */
  int BETWEEN = 24;
  /** RegularExpression Id. */
  int IN = 25;
  /** RegularExpression Id. */
  int PLACEHOLDER = 26;
  /** RegularExpression Id. */
  int ASC = 27;
  /** RegularExpression Id. */
  int DESC = 28;
  /** RegularExpression Id. */
  int DAYOFMONTH = 29;
  /** RegularExpression Id. */
  int MONTH = 30;
  /** RegularExpression Id. */
  int YEAR = 31;
  /** RegularExpression Id. */
  int HOUROFDAY = 32;
  /** RegularExpression Id. */
  int MINUTE = 33;
  /** RegularExpression Id. */
  int SECOND = 34;
  /** RegularExpression Id. */
  int LOWER = 35;
  /** RegularExpression Id. */
  int ROUND = 36;
  /** RegularExpression Id. */
  int UPPER = 37;
  /** RegularExpression Id. */
  int LENGTH = 38;
  /** RegularExpression Id. */
  int NULLIF = 39;
  /** RegularExpression Id. */
  int COUNT = 40;
  /** RegularExpression Id. */
  int MAX = 41;
  /** RegularExpression Id. */
  int MIN = 42;
  /** RegularExpression Id. */
  int SUM = 43;
  /** RegularExpression Id. */
  int AVG = 44;
  /** RegularExpression Id. */
  int FROM = 45;
  /** RegularExpression Id. */
  int WHERE = 46;
  /** RegularExpression Id. */
  int GROUP = 47;
  /** RegularExpression Id. */
  int ORDER = 48;
  /** RegularExpression Id. */
  int BY = 49;
  /** RegularExpression Id. */
  int HAVING = 50;
  /** RegularExpression Id. */
  int LIMIT = 51;
  /** RegularExpression Id. */
  int OFFSET = 52;
  /** RegularExpression Id. */
  int NAME = 53;
  /** RegularExpression Id. */
  int STRING = 54;
  /** RegularExpression Id. */
  int RELOP = 55;
  /** RegularExpression Id. */
  int ASTERISK = 56;
  /** RegularExpression Id. */
  int NAMEASTERISK = 57;
  /** RegularExpression Id. */
  int MINUS = 58;
  /** RegularExpression Id. */
  int PLUS = 59;
  /** RegularExpression Id. */
  int DIVIDE = 60;
  /** RegularExpression Id. */
  int MODULO = 61;
  /** RegularExpression Id. */
  int OPENPARENTHESIS = 62;
  /** RegularExpression Id. */
  int CLOSEPARENTHESIS = 63;
  /** RegularExpression Id. */
  int SEMICOLON = 64;
  /** RegularExpression Id. */
  int TABLENAME = 69;
  /** RegularExpression Id. */
  int QUOTEDTABLENAME = 70;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 71;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_TABLE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLELINECOMMENT>",
    "\"SELECT\"",
    "\"DISTINCT\"",
    "\",\"",
    "\".\"",
    "<UNSIGNEDINT>",
    "<UNSIGNEDNUMBER>",
    "<DIGITS>",
    "<EXPONENT>",
    "\"L\"",
    "\"NULL\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_TIME\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"IS\"",
    "\"AS\"",
    "\"LIKE\"",
    "\"BETWEEN\"",
    "\"IN\"",
    "\"?\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"DAYOFMONTH\"",
    "\"MONTH\"",
    "\"YEAR\"",
    "\"HOUROFDAY\"",
    "\"MINUTE\"",
    "\"SECOND\"",
    "\"LOWER\"",
    "\"ROUND\"",
    "\"UPPER\"",
    "\"LENGTH\"",
    "\"NULLIF\"",
    "\"COUNT\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"SUM\"",
    "\"AVG\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"GROUP\"",
    "\"ORDER\"",
    "\"BY\"",
    "\"HAVING\"",
    "\"LIMIT\"",
    "\"OFFSET\"",
    "<NAME>",
    "<STRING>",
    "<RELOP>",
    "\"*\"",
    "<NAMEASTERISK>",
    "\"-\"",
    "\"+\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<TABLENAME>",
    "<QUOTEDTABLENAME>",
    "<UNEXPECTED_CHAR>",
  };

}
