/* Generated By:JavaCC: Do not edit this line. ExpressionParser.java */
package org.relique.jdbc.csv;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.math.BigInteger;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.LinkedList;
import org.relique.jdbc.csv.Expression;
class NumericConstant extends Expression{
  Number value;
  public NumericConstant(Number d){
    value = d;
  }
  public Object eval(Map env){
    return value;
  }
  public String toString(){
    return value.toString();
  }
  public List usedColumns(){
    return new LinkedList();
  }
}
class StringConstant extends Expression{
  String value;
  public StringConstant(String s){
    value = s;
  }
  public Object eval(Map env){
    return value;
  }
  public String toString(){
    return "'"+value+"'";
  }
  public List usedColumns(){
    return new LinkedList();
  }
}
class Placeholder extends Expression{
  static int nextIndex = 1;
  Integer index;
  public Placeholder(){
    index = Integer.valueOf(nextIndex);
    nextIndex++;
  }
  public Object eval(Map env){
    return env.get(index);
  }
  public String toString(){
    return "?";
  }
  public List usedColumns(){
    return new LinkedList();
  }
}
class ColumnName extends Expression{
  String columnName;
  public ColumnName(String columnName){
    this .columnName = columnName.toUpperCase();
  }
  public Object eval(Map env){
    return env.get(columnName);
  }
  public String toString(){
    return "["+columnName+"]";
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.add(columnName);
    return result;
  }
}
class QueryEnvEntry extends Expression{
  String key;
  Expression expression;
  public QueryEnvEntry(String fieldName){
    this .key = fieldName.toUpperCase();
    this .expression = new ColumnName(fieldName);
  }
  public QueryEnvEntry(String fieldName, Expression exp){
    this .key = fieldName.toUpperCase();
    this .expression = exp;
  }
  public Object eval(Map env){
    return expression.eval(env);
  }
  public String toString(){
    return key+": "+expression.toString();
  }
}
class BinaryOperation extends Expression{
  char op;
  Expression left, right;
  public BinaryOperation(char op, Expression left, Expression right){
    this .op = op;
    this .left = left;
    this .right = right;
  }
  public Object eval(Map env){
    Object leftEval = left.eval(env);
    Object rightEval = right.eval(env);
    try {
      Integer leftInt = (Integer)leftEval;
      BigInteger bil = new BigInteger(leftInt.toString());
      Integer rightInt = (Integer)rightEval;
      BigInteger bir = new BigInteger(rightInt.toString());
      if (op == '+')return new Integer(bil.add(bir).toString());
      if (op == '-')return new Integer(bil.subtract(bir).toString());
      if (op == '*')return new Integer(bil.multiply(bir).toString());
      if (op == '/')return new Integer(bil.divide(bir).toString());
    }
    catch (ClassCastException e){}try {
      Number leftN = (Number)leftEval;
      BigDecimal bdl = new BigDecimal(leftN.toString());
      Number rightN = (Number)rightEval;
      BigDecimal bdr = new BigDecimal(rightN.toString());
      if (op == '+')return new Double(bdl.add(bdr).toString());
      if (op == '-')return new Double(bdl.subtract(bdr).toString());
      if (op == '*')return new Double(bdl.multiply(bdr).toString());
      MathContext mc = new MathContext("precision=14 roundingMode=HALF_UP");
      if (op == '/')return new Double(bdl.divide(bdr, mc.getPrecision(), mc.getRoundingMode()).toString());
    }
    catch (ClassCastException e){}try {
      if (op == '+'){
        Date leftD = (Date)leftEval;
        Time rightT = (Time)rightEval;
        Expression stringConverter = new ColumnName("@StringConverter");
        StringConverter sc = (StringConverter) stringConverter.eval(env);
        return sc.parseTimestamp(leftD.toString() + " " + rightT.toString());
      }
    }
    catch (ClassCastException e){}try {
      if (op == '+' || op == '-'){
        Timestamp leftD = (Timestamp)leftEval;
        long time = leftD.getTime();
        Number rightN = (Number)rightEval;
        BigDecimal bdr = new BigDecimal(rightN.toString());
        if (op == '+')return new Timestamp(time + bdr.longValue());
        if (op == '-')return new Timestamp(time - bdr.longValue());
      }
    }
    catch (ClassCastException e){}
    if(op == '+')return ""+leftEval+rightEval;
    return null;
  }
  public String toString(){
    return ""+op+" "+left+" "+right;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(left.usedColumns());
    result.addAll(right.usedColumns());
    return result;
  }
}
abstract class LogicalExpression extends Expression{
  public boolean isTrue(Map env){
    return false;
  }
}
class ParsedExpression extends LogicalExpression{
  public Expression content;
  public ParsedExpression(Expression left){
    content = left;
  }
  public boolean isTrue(Map env){
    return ((LogicalExpression)content).isTrue(env);
  }
  public Object eval(Map env){
    return content.eval(env);
  }
  public String toString(){
    return content.toString();
  }
  public List usedColumns(){
    return content.usedColumns();
  }
}
class NotExpression extends LogicalExpression{
  LogicalExpression content;
  public NotExpression(LogicalExpression arg){
    this .content = arg;
  }
  public boolean isTrue(Map env){
    return !content.isTrue(env);
  }
  public String toString(){
    return "NOT "+content;
  }
  public List usedColumns(){
    return content.usedColumns();
  }
}
class OrExpression extends LogicalExpression{
  LogicalExpression left, right;
  public OrExpression(LogicalExpression left, LogicalExpression right){
    this .left = left;
    this .right = right;
  }
  public boolean isTrue(Map env){
    return left.isTrue(env) || right.isTrue(env);
  }
  public String toString(){
    return "OR "+left+" "+right;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(left.usedColumns());
    result.addAll(right.usedColumns());
    return result;
  }
}
class AndExpression extends LogicalExpression{
  LogicalExpression left, right;
  public AndExpression(LogicalExpression left, LogicalExpression right){
    this .left = left;
    this .right = right;
  }
  public boolean isTrue(Map env){
    return left.isTrue(env) && right.isTrue(env);
  }
  public String toString(){
    return "AND "+left+" "+right;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(left.usedColumns());
    result.addAll(right.usedColumns());
    return result;
  }
}
class RelopExpression extends LogicalExpression{
  String op;
  Expression left, right;
  public RelopExpression(String op, Expression left, Expression right){
    this .op = op;
    this .left = left;
    this .right = right;
  }
  public boolean isTrue(Map env){
    Comparable leftValue = (Comparable)left.eval(env);
    Comparable rightValue = (Comparable)right.eval(env);
    boolean result = false;
    Integer leftComparedToRightObj = null;
    try {
      leftComparedToRightObj = new Integer(leftValue.compareTo(rightValue));
    }
    catch (ClassCastException e){}try {
      Double leftDouble = new Double(((Number)leftValue).toString());
      Double rightDouble = new Double(((Number)rightValue).toString());
      leftComparedToRightObj = new Integer(leftDouble.compareTo(rightDouble));
    }
    catch (ClassCastException e){}catch (NumberFormatException e){}if (leftComparedToRightObj != null){
      int leftComparedToRight = leftComparedToRightObj.intValue();
      if (leftValue != null && rightValue != null){
        if (op.equals("=")){
          result = leftComparedToRight == 0;
        }
        else if (op.equals("<>") || op.equals("!=")){
          result = leftComparedToRight != 0;
        }
        else if (op.equals(">")){
          result = leftComparedToRight>0;
        }
        else if (op.equals("<")){
          result = leftComparedToRight<0;
        }
        else if (op.equals("<=") || op.equals("=<")){
          result = leftComparedToRight <= 0;
        }
        else if (op.equals(">=") || op.equals("=>")){
          result = leftComparedToRight >= 0;
        }
      }
    }
    return result;
  }
  public String toString(){
    return op+" "+left+" "+right;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(left.usedColumns());
    result.addAll(right.usedColumns());
    return result;
  }
}
class BetweenExpression extends LogicalExpression{
  Expression obj, left, right;
  public BetweenExpression(Expression obj, Expression left, Expression right){
    this .obj = obj;
    this .left = left;
    this .right = right;
  }
  public boolean isTrue(Map env){
    Comparable leftValue = (Comparable)left.eval(env);
    Comparable rightValue = (Comparable)right.eval(env);
    Comparable objValue = (Comparable)obj.eval(env);
    boolean result = true;
    try {
      if (objValue.compareTo(leftValue)<0)result = false;
      if (objValue.compareTo(rightValue)>0)result = false;
    }
    catch (ClassCastException e){}return result;
  }
  public String toString(){
    return "B "+obj+" "+left+" "+right;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(obj.usedColumns());
    result.addAll(left.usedColumns());
    result.addAll(right.usedColumns());
    return result;
  }
}
class IsNullExpression extends LogicalExpression{
  Expression arg;
  public IsNullExpression(Expression arg){
    this .arg = arg;
  }
  public boolean isTrue(Map env){
    Object o = arg.eval(env);
    return (o == null);
  }
  public String toString(){
    return "N "+arg;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(arg.usedColumns());
    return result;
  }
}
class LikeExpression extends LogicalExpression{
  Expression arg1, arg2;
  public LikeExpression(Expression arg1, Expression arg2){
    this .arg1 = arg1;
    this .arg2 = arg2;
  }
  public boolean isTrue(Map env){
    Object left = arg1.eval(env);
    Object right = arg2.eval(env);
    boolean result = false;
    if (left != null && right != null)
      result = LikePattern.matches(right.toString(), left.toString());
    return result;
  }
  public String toString(){
    return "L "+arg1+" "+arg2;
  }
  public List usedColumns(){
    List result = new LinkedList();
    result.addAll(arg1.usedColumns());
    result.addAll(arg2.usedColumns());
    return result;
  }
}
public class ExpressionParser implements ExpressionParserConstants {
  ParsedExpression content;
  private Map placeholders;
  public void parseLogicalExpression()throws ParseException{
    Placeholder.nextIndex = 1;
    placeholders = new HashMap();
    content = logicalExpression();
  }
  public void parseQueryEnvEntry()throws ParseException{
    content = queryEnvEntry();
  }
  public boolean isTrue(Map env){
    if(placeholders != null) {
      Map useThisEnv = new HashMap();
      useThisEnv.putAll(env);
      useThisEnv.putAll(placeholders);
      env = useThisEnv;
    }
    return content.isTrue(env);
  }
  public Object eval(Map env){
    if(placeholders != null) {
      Map useThisEnv = new HashMap();
      useThisEnv.putAll(env);
      useThisEnv.putAll(placeholders);
      env = useThisEnv;
    }
    return content.eval(env);
  }
  public String toString(){
    return ""+content;
  }
  public List usedColumns(){
    return content.usedColumns();
  }
  public int getPlaceholdersCount(){
    return Placeholder.nextIndex - 1;
  }
  public void setPlaceholdersValues(Object[] values){
    for(int i=1; i<values.length; i++){
      placeholders.put(Integer.valueOf(i), values[i]);
    }
  }

  final public ParsedExpression logicalExpression() throws ParseException {
  LogicalExpression left;
    left = logicalOrExpression();
    jj_consume_token(0);
    {if (true) return new ParsedExpression(left);}
    throw new Error("Missing return statement in function");
  }

  final public ParsedExpression queryEnvEntry() throws ParseException {
  Expression expression, alias, result;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case UNSIGNEDNUMBER:
    case NULL:
    case PLACEHOLDER:
    case NAME:
    case STRING:
    case MINUS:
    result = null;
      expression = binaryOperation();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AS:
      case NAME:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AS:
          jj_consume_token(AS);
          break;
        default:
          jj_la1[0] = jj_gen;
          ;
        }
        alias = columnName();
    result = new QueryEnvEntry(((ColumnName)alias).columnName, expression);
        break;
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      jj_consume_token(0);
    if (result == null){
      try {
        result = new QueryEnvEntry(((ColumnName)expression).columnName, expression);
      }
      catch (ClassCastException e){
        {if (true) throw new ParseException("can't accept expression '"+expression+"' without an alias");}
      }
    }
    {if (true) return new ParsedExpression(result);}
      break;
    case ASTERISK:
      jj_consume_token(ASTERISK);
    {if (true) return null;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public LogicalExpression logicalOrExpression() throws ParseException {
  LogicalExpression left, right;
    left = logicalAndExpression();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_1;
      }
      jj_consume_token(OR);
      right = logicalAndExpression();
    left = new OrExpression(left, right);
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public LogicalExpression logicalAndExpression() throws ParseException {
  LogicalExpression left, right;
    left = logicalUnaryExpression();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      jj_consume_token(AND);
      right = logicalUnaryExpression();
    left = new AndExpression(left, right);
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public LogicalExpression logicalUnaryExpression() throws ParseException {
  LogicalExpression arg;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      arg = logicalUnaryExpression();
    {if (true) return new NotExpression(arg);}
      break;
    case 22:
      jj_consume_token(22);
      arg = logicalOrExpression();
      jj_consume_token(23);
    {if (true) return arg;}
      break;
    case UNSIGNEDNUMBER:
    case NULL:
    case PLACEHOLDER:
    case NAME:
    case STRING:
    case MINUS:
      arg = relationalExpression();
    {if (true) return arg;}
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public LogicalExpression relationalExpression() throws ParseException {
  Expression arg1, arg2, arg3;
  String op;
  Token t;
    arg1 = simpleExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RELOP:
      op = relOp();
      arg2 = simpleExpression();
    {if (true) return new RelopExpression(op, arg1, arg2);}
      break;
    case BETWEEN:
      jj_consume_token(BETWEEN);
      arg2 = simpleExpression();
      jj_consume_token(AND);
      arg3 = simpleExpression();
    {if (true) return new BetweenExpression(arg1, arg2, arg3);}
      break;
    case IS:
      jj_consume_token(IS);
      jj_consume_token(NULL);
    {if (true) return new IsNullExpression(arg1);}
      break;
    case LIKE:
      jj_consume_token(LIKE);
      t = jj_consume_token(STRING);
    {if (true) return new LikeExpression(arg1, new StringConstant(t.image.substring(1, t.image.length()-1)));}
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String relOp() throws ParseException {
  Token t;
    t = jj_consume_token(RELOP);
    {if (true) return new String(t.image);}
    throw new Error("Missing return statement in function");
  }

  final public char binOp() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BINOP:
      t = jj_consume_token(BINOP);
      break;
    case ASTERISK:
      t = jj_consume_token(ASTERISK);
      break;
    case MINUS:
      t = jj_consume_token(MINUS);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return t.image.charAt(0);}
    throw new Error("Missing return statement in function");
  }

  final public Expression binaryOperation() throws ParseException {
  Expression left, right;
  char op;
    left = simpleExpression();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASTERISK:
      case MINUS:
      case BINOP:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      op = binOp();
      right = simpleExpression();
    left = new BinaryOperation(op, left, right);
    }
    {if (true) return left;}
    throw new Error("Missing return statement in function");
  }

  final public Expression simpleExpression() throws ParseException {
  Expression arg;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      arg = columnName();
    {if (true) return arg;}
      break;
    case UNSIGNEDNUMBER:
    case MINUS:
      arg = numericConstant();
    {if (true) return arg;}
      break;
    case STRING:
      arg = stringConstant();
    {if (true) return arg;}
      break;
    case NULL:
      jj_consume_token(NULL);
    {if (true) return null;}
      break;
    case PLACEHOLDER:
      jj_consume_token(PLACEHOLDER);
    {if (true) return new Placeholder();}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Expression columnName() throws ParseException {
  Token t;
    t = jj_consume_token(NAME);
    {if (true) return new ColumnName(t.image);}
    throw new Error("Missing return statement in function");
  }

  final public Expression numericConstant() throws ParseException {
  Token t;
  String sign;
   sign="";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      t = jj_consume_token(MINUS);
             sign=t.image;
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    t = jj_consume_token(UNSIGNEDNUMBER);
    Number value = null;
    try {
      value = new Integer(sign+t.image);
    }
    catch (NumberFormatException e){
      value = new Double(sign+t.image);
    }
    {if (true) return new NumericConstant(value);}
    throw new Error("Missing return statement in function");
  }

  final public Expression stringConstant() throws ParseException {
  String left, right;
    left = stringConstantAtom();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_4;
      }
      right = stringConstantAtom();
    left = left+"'"+right;
    }
    {if (true) return new StringConstant(left);}
    throw new Error("Missing return statement in function");
  }

  final public String stringConstantAtom() throws ParseException {
  Token t;
    t = jj_consume_token(STRING);
    {if (true) return t.image.substring(1, t.image.length()-1);}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ExpressionParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[12];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1000,0x11000,0x1b8090,0x200,0x100,0x538490,0x46800,0x380000,0x380000,0x138090,0x100000,0x20000,};
   }

  /** Constructor with InputStream. */
  public ExpressionParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ExpressionParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.getMessage()); }
    token_source = new ExpressionParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.getMessage()); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ExpressionParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ExpressionParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ExpressionParser(ExpressionParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ExpressionParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 12; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[24];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 12; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 24; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
