/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package org.relique.jdbc.csv;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNSIGNEDNUMBER = 5;
  /** RegularExpression Id. */
  int DIGITS = 6;
  /** RegularExpression Id. */
  int EXPONENT = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int IS = 12;
  /** RegularExpression Id. */
  int AS = 13;
  /** RegularExpression Id. */
  int LIKE = 14;
  /** RegularExpression Id. */
  int BETWEEN = 15;
  /** RegularExpression Id. */
  int PLACEHOLDER = 16;
  /** RegularExpression Id. */
  int ASC = 17;
  /** RegularExpression Id. */
  int DESC = 18;
  /** RegularExpression Id. */
  int LOWER = 19;
  /** RegularExpression Id. */
  int ROUND = 20;
  /** RegularExpression Id. */
  int UPPER = 21;
  /** RegularExpression Id. */
  int COUNT = 22;
  /** RegularExpression Id. */
  int MAX = 23;
  /** RegularExpression Id. */
  int MIN = 24;
  /** RegularExpression Id. */
  int NAME = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int RELOP = 27;
  /** RegularExpression Id. */
  int ASTERISK = 28;
  /** RegularExpression Id. */
  int NAMEASTERISK = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int DIVIDE = 32;
  /** RegularExpression Id. */
  int OPENPARENTHESIS = 33;
  /** RegularExpression Id. */
  int CLOSEPARENTHESIS = 34;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<UNSIGNEDNUMBER>",
    "<DIGITS>",
    "<EXPONENT>",
    "\"NULL\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"IS\"",
    "\"AS\"",
    "\"LIKE\"",
    "\"BETWEEN\"",
    "\"?\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"LOWER\"",
    "\"ROUND\"",
    "\"UPPER\"",
    "\"COUNT\"",
    "\"MAX\"",
    "\"MIN\"",
    "<NAME>",
    "<STRING>",
    "<RELOP>",
    "\"*\"",
    "<NAMEASTERISK>",
    "\"-\"",
    "\"+\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<UNEXPECTED_CHAR>",
  };

}
